/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    'sanctum.csrf-cookie': [];
    'ignition.healthCheck': [];
    'ignition.executeSolution': [];
    'ignition.updateConfig': [];
    'auth.register.view': [];
    'auth.login.view': [];
    'auth.register': [];
    'auth.login': [];
    'auth.logout': [];
    'seri.index': [];
    'seri.detail': [
      {
        name: 'id';
      },
    ];
    'cart.create': [];
    'cart.delete': [
      {
        name: 'id';
      },
    ];
    'cart.delete.volume': [
      {
        name: 'id';
      },
    ];
  }
}
export {};
