/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    'sanctum.csrf-cookie': [];
    'ignition.healthCheck': [];
    'ignition.executeSolution': [];
    'ignition.updateConfig': [];
    register: [];
    login: [];
    logout: [];
    'create-cart': [];
    'delete-cart': [
      {
        name: 'id';
      },
    ];
    'delete-cart-volume': [
      {
        name: 'id';
      },
    ];
    home: [];
    'sign-in': [];
    'sign-up': [];
  }
}
export {};
