/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    'sanctum.csrf-cookie': [];
    'ignition.healthCheck': [];
    'ignition.executeSolution': [];
    'ignition.updateConfig': [];
    'auth.register.view': [];
    'auth.login.view': [];
    'auth.register': [];
    'auth.login': [];
    'auth.logout': [];
    'create-cart': [];
    'delete-cart': [
      {
        name: 'id';
      },
    ];
    'delete-cart-volume': [
      {
        name: 'id';
      },
    ];
    home: [];
  }
}
export {};
